name: Build SkinChanger

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "gradle/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - ".github/workflows/test.yml"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    strategy:
      fail-fast: true
      matrix:
        java: [8, 11, 17, 21]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }} for x64
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run test builds
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: build

