name: Test SkinChanger

on:
  push:
    branches:
      - main
      - development
    paths:
      - "src/**"
      - "gradle/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "src/**"
      - "gradle/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}